import admin from 'firebase-admin'
import dotenv from 'dotenv'

dotenv.config()
admin.initializeApp()

export {
  // This part is automatically generated by Skeet Framework.
  // Please do not edit this part.
  // Skeet Doc: https://skeet.dev
  root,
  authOnCreateUser,
  createStreamChatMessage,
  createVertexMessage,
} from '@/routings'
